### ISSUE TITLE
Suspicious domains: <xstellar.so>

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#12]
### Specific Domain(s)
xstellar.so

### The reason why you think we need to blacklist these domains
scamming people/fake assets.

### The source where suspicious domains are mentioned (e.g. Telegram groups, WhatsApp, Facebook, etc)
Telegram groups

### Other comments about suspicious domains
This domain stole my money with fake assets!

**Comment by CryptoHobbyist** [comment]
There are a huge list of Red Flags with any of the xtellar.so tokens. Least of which is they have not been active on the website since  November 2021. 
I have put this document together to help evaluate token projects. 
At the very least check their website and look them up on sellar.expert. If they are illegally using the brands and logos of real world assets THAT IS A HUGE RED FLAG.

https://docs.google.com/document/d/1Vbo1GsQWSsTCeVw0nMLX6X7tPCufXMNRTmeUvQh7tmo/edit?usp=sharing

**Comment by star-dust-one** [comment]
Thanks. This "xstellar.so" was added to our blacklist.
